2025-06-08 12:16:02,390 [INFO] [server.py:<module>] Server starting
2025-06-08 12:16:02,458 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:16:19,242 [INFO] [device.py:<module>] Device started
2025-06-08 12:16:19,310 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:16:19,310 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:16:19,310 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 56807)
2025-06-08 12:16:19,310 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:16:19,310 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:16:19,310 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:16:19,310 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:16:19,310 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:16:19,310 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:16:19,310 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:16:19,310 [INFO] [device.py:send_certificate] Sent certificate length: 881
2025-06-08 12:16:19,310 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:16:19,310 [INFO] [device.py:send_certificate] Sent certificate
2025-06-08 12:16:19,310 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:16:19,310 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:16:19,310 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:16:19,310 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:16:19,310 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:16:19,310 [ERROR] [device.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 46, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 12:16:19,311 [ERROR] [device.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 123, in send_hello
    send_certificate(client_socket, "certificates/device_certificate.json")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/device.py", line 50, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/device.py", line 46, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 12:16:19,314 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:16:19,315 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:16:19,315 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:16:19,316 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 155, in <module>
    nonce_device = recv_exact(client, 16)
  File "/Users/omerfarukbulut/info_sec/server.py", line 32, in recv_exact
    packet = sock.recv(size - len(data))
ConnectionResetError: [Errno 54] Connection reset by peer
2025-06-08 12:16:19,317 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:18:28,102 [INFO] [server.py:<module>] Server starting
2025-06-08 12:18:28,169 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:18:30,599 [INFO] [device.py:<module>] Device started
2025-06-08 12:18:30,666 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:18:30,666 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:18:30,666 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 56825)
2025-06-08 12:18:30,666 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:18:30,667 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:18:30,667 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:18:30,667 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:18:30,667 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:18:30,667 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:18:30,667 [INFO] [device.py:send_certificate] Sent certificate length: 881
2025-06-08 12:18:30,667 [INFO] [device.py:send_certificate] Sent certificate
2025-06-08 12:18:30,667 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:18:30,667 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:18:30,667 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:18:30,667 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:18:30,667 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:18:30,667 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:18:30,671 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:18:30,672 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:18:30,672 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:18:30,674 [INFO] [device.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:18:30,674 [INFO] [device.py:send_hello] Sent nonce: b'\xceY\xd99\xe7z%\x9b:7\xfb\xdb\xac|\xfb\x8b'
2025-06-08 12:18:30,674 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 12:18:30,674 [INFO] [server.py:<module>] Received nonce: b'\xceY\xd99\xe7z%\x9b:7\xfb\xdb\xac|\xfb\x8b'
2025-06-08 12:18:30,674 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 12:18:30,674 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:18:30,674 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:18:30,675 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 12:18:30,675 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 12:18:30,675 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:18:30,675 [INFO] [device.py:<module>] Device socket closed
2025-06-08 12:18:30,675 [INFO] [server.py:<module>] Received header: b'<ENDD>'
2025-06-08 12:18:30,675 [INFO] [server.py:<module>] Received end of file
2025-06-08 12:18:30,675 [INFO] [server.py:<module>] Server closed
2025-06-08 12:18:30,676 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:27:21,572 [INFO] [server.py:<module>] Server starting
2025-06-08 12:27:21,640 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:27:23,850 [INFO] [device.py:<module>] Device started
2025-06-08 12:27:23,919 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:27:23,919 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:27:23,919 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 56915)
2025-06-08 12:27:23,919 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:27:23,919 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:27:23,919 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:27:23,919 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:27:23,919 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:27:23,919 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:27:23,919 [ERROR] [device.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 108, in send_hello
    send_certificate(client_socket, "certificates/device_certificate.json")
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: send_certificate() missing 1 required positional argument: 'private_key'
2025-06-08 12:27:23,923 [WARNING] [server.py:recv_exact] Connection interrupted during receive
2025-06-08 12:27:23,923 [INFO] [server.py:recv_exact] Received 0 bytes successfully
2025-06-08 12:27:23,923 [INFO] [server.py:recv_certificate] Length bytes (raw): 
2025-06-08 12:27:23,923 [INFO] [server.py:recv_certificate] Expecting certificate of 0 bytes
2025-06-08 12:27:23,923 [INFO] [server.py:recv_exact] Receiving exactly 0 bytes...
2025-06-08 12:27:23,923 [INFO] [server.py:recv_exact] Received 0 bytes successfully
2025-06-08 12:27:23,923 [ERROR] [server.py:recv_certificate] Failed to receive or validate certificate.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 50, in recv_certificate
    cert_bundle = json.loads(cert_data.decode())
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/decoder.py", line 345, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.13/3.13.3/Frameworks/Python.framework/Versions/3.13/lib/python3.13/json/decoder.py", line 363, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-06-08 12:27:23,925 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 146, in <module>
    if validate_certificate(certificate, ca_public_key):
       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 49, in validate_certificate
    cert_data = cert_bundle["certificate"]
                ~~~~~~~~~~~^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2025-06-08 12:27:23,925 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:27:53,305 [INFO] [server.py:<module>] Server starting
2025-06-08 12:27:53,372 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:27:54,767 [INFO] [device.py:<module>] Device started
2025-06-08 12:27:54,835 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:27:54,835 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:27:54,835 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 56920)
2025-06-08 12:27:54,835 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:27:54,835 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:27:54,835 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:27:54,835 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:27:54,835 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:27:54,835 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:27:54,836 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:27:54,836 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:27:54,836 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:27:54,836 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:27:54,836 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:27:54,836 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:27:54,836 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:27:54,836 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:27:54,839 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:27:54,840 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:27:54,840 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:27:54,840 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:27:54,841 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:27:54,842 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:27:54,842 [INFO] [device.py:send_hello] Sent nonce: b'\x0f\xfd\x1f\xfe\x94\xe3^\xf6\xe3vs\xd5k\xae\x05.'
2025-06-08 12:27:54,842 [ERROR] [ca_cert.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 16 bytes, expected 256 bytes.
2025-06-08 12:27:54,844 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", server_public_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 16 bytes, expected 256 bytes.
2025-06-08 12:27:54,844 [ERROR] [device.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 80, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 113, in send_hello
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 12:27:54,844 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 148, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 81, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", server_public_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 16 bytes, expected 256 bytes.
2025-06-08 12:27:54,845 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:29:45,020 [INFO] [server.py:<module>] Server starting
2025-06-08 12:29:45,088 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:29:46,931 [INFO] [device.py:<module>] Device started
2025-06-08 12:29:46,998 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:29:46,998 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:29:46,998 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 56934)
2025-06-08 12:29:46,998 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:29:46,998 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:29:46,999 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:29:46,999 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:29:46,999 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:29:46,999 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:29:47,000 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:29:47,000 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:29:47,000 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:29:47,000 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:29:47,000 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:29:47,000 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:29:47,000 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:29:47,000 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:29:47,002 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:29:47,004 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:29:47,004 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:29:47,004 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:29:47,005 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:29:47,005 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:29:47,005 [INFO] [device.py:send_hello] Sent nonce: b"&W\xdaK\xe0|N\x13\x89;Q'I)\xf0\xc4"
2025-06-08 12:29:47,005 [ERROR] [ca_cert.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 16 bytes, expected 256 bytes.
2025-06-08 12:29:47,007 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 16 bytes, expected 256 bytes.
2025-06-08 12:29:47,007 [ERROR] [device.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 80, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 113, in send_hello
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 12:29:47,008 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 148, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 81, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 16 bytes, expected 256 bytes.
2025-06-08 12:29:47,008 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:30:01,950 [INFO] [server.py:<module>] Server starting
2025-06-08 12:30:02,017 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:30:03,616 [INFO] [device.py:<module>] Device started
2025-06-08 12:30:03,683 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:30:03,683 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:30:03,683 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 56935)
2025-06-08 12:30:03,683 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:30:03,683 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:30:03,683 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:30:03,683 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:30:03,683 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:30:03,683 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:30:03,684 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:30:03,684 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:30:03,684 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:30:03,684 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:30:03,684 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:30:03,684 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:30:03,684 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:30:03,684 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:30:03,687 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:30:03,689 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:30:03,689 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:30:03,689 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:30:03,690 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:30:03,690 [INFO] [device.py:send_hello] Sent nonce: b'\xf47z\xc0E\xf5\xcf!]\xc4T\xf0v)4s'
2025-06-08 12:30:03,690 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 12:30:03,690 [INFO] [server.py:<module>] Received nonce: b'\xf47z\xc0E\xf5\xcf!]\xc4T\xf0v)4s'
2025-06-08 12:30:03,691 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 12:30:03,691 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:30:03,690 [ERROR] [device.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 113, in send_hello
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 12:30:03,695 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 87, in <module>
    header = recv_exact(client, 6)
  File "/Users/omerfarukbulut/info_sec/server.py", line 32, in recv_exact
    packet = sock.recv(size - len(data))
ConnectionResetError: [Errno 54] Connection reset by peer
2025-06-08 12:30:03,696 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:31:07,991 [INFO] [server.py:<module>] Server starting
2025-06-08 12:31:08,059 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:31:09,635 [INFO] [device.py:<module>] Device started
2025-06-08 12:31:09,702 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:31:09,702 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:31:09,702 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 56944)
2025-06-08 12:31:09,702 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:31:09,702 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:31:09,702 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:31:09,702 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:31:09,702 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:31:09,702 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:31:09,702 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:31:09,702 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:31:09,702 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:31:09,702 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:31:09,702 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:31:09,702 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:31:09,702 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:31:09,702 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:31:09,706 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:31:09,707 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:31:09,707 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:31:09,709 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:31:09,709 [INFO] [device.py:send_hello] Sent nonce: b'\x90\\\xf8\x9a\xc4\xe3\xfb\x87\x9623\x82(\xde\x1f-'
2025-06-08 12:31:09,709 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 12:31:09,709 [INFO] [server.py:<module>] Received nonce: b'\x90\\\xf8\x9a\xc4\xe3\xfb\x87\x9623\x82(\xde\x1f-'
2025-06-08 12:31:09,709 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 12:31:09,709 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:31:09,709 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:31:09,710 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 12:31:09,710 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 12:31:09,710 [INFO] [device.py:<module>] Device socket closed
2025-06-08 12:31:09,710 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:31:09,710 [INFO] [server.py:<module>] Received header: b'<ENDD>'
2025-06-08 12:31:09,710 [INFO] [server.py:<module>] Received end of file
2025-06-08 12:31:09,710 [INFO] [server.py:<module>] Server closed
2025-06-08 12:31:09,710 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:34:07,420 [INFO] [server.py:<module>] Server starting
2025-06-08 12:34:07,489 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:34:09,668 [INFO] [device.py:<module>] Device started
2025-06-08 12:34:09,735 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:34:09,736 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:34:09,736 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 56968)
2025-06-08 12:34:09,736 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:34:09,736 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:34:09,736 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:34:09,736 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:34:09,736 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:34:09,736 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:34:09,737 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:34:09,737 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:34:09,737 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:34:09,737 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:34:09,737 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:34:09,737 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:34:09,737 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:34:09,737 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:34:09,740 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:34:09,741 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:34:09,741 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:34:09,742 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:34:09,743 [INFO] [device.py:send_hello] Sent nonce: b'H\xef\x9a\xd9no%\xd4\xd2@lPD\x88\xa0j'
2025-06-08 12:34:09,743 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 12:34:09,743 [INFO] [server.py:<module>] Received nonce: b'H\xef\x9a\xd9no%\xd4\xd2@lPD\x88\xa0j'
2025-06-08 12:34:09,743 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 12:34:09,743 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:34:09,743 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:34:09,743 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:34:09,744 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 12:34:09,744 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 12:34:09,744 [INFO] [device.py:<module>] Device socket closed
2025-06-08 12:34:09,744 [ERROR] [ca_cert.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 12:34:09,745 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 12:34:09,746 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 163, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 81, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 12:34:09,746 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:48:49,527 [INFO] [server.py:<module>] Server starting
2025-06-08 12:48:49,594 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:48:50,919 [INFO] [device.py:<module>] Device started
2025-06-08 12:48:50,986 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:48:50,986 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 58464)
2025-06-08 12:48:50,986 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:48:50,986 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:48:50,986 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:48:50,987 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:48:50,987 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:48:50,987 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:48:50,987 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:48:50,987 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:48:50,987 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:48:50,987 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:48:50,987 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:48:50,987 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:48:50,987 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:48:50,987 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:48:50,987 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:48:50,989 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:48:50,989 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:48:50,990 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:48:50,992 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:48:50,992 [INFO] [device.py:send_hello] Sent nonce: b'\xec\xaf\x05\x8ciQ!\x10\xa2h\xc8e\x03\xe0\x81\x80'
2025-06-08 12:48:50,992 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 12:48:50,992 [INFO] [server.py:<module>] Received nonce: b'\xec\xaf\x05\x8ciQ!\x10\xa2h\xc8e\x03\xe0\x81\x80'
2025-06-08 12:48:50,992 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 12:48:50,992 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:48:50,992 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:48:50,992 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:48:50,993 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 12:48:50,993 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 12:48:50,993 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 12:48:50,993 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 12:48:50,993 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 12:48:50,993 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 12:48:50,993 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 12:51:50,054 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:51:50,054 [INFO] [device.py:recv_hello] Received nonce: b''
2025-06-08 12:51:50,056 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 12:51:50,057 [ERROR] [device.py:send_end_of_file] Failed to send end of file
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 97, in send_end_of_file
    client_socket.sendall(b"<ENDD>")
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-06-08 12:51:52,003 [INFO] [server.py:<module>] Server starting
2025-06-08 12:51:52,070 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:51:54,248 [INFO] [device.py:<module>] Device started
2025-06-08 12:51:54,318 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:51:54,318 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 58490)
2025-06-08 12:51:54,318 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:51:54,318 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:51:54,318 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:51:54,318 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:51:54,318 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:51:54,318 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:51:54,318 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:51:54,319 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:51:54,319 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:51:54,319 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:51:54,319 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:51:54,319 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:51:54,319 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:51:54,319 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:51:54,319 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:51:54,320 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:51:54,320 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:51:54,320 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:51:54,322 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:51:54,322 [INFO] [device.py:send_hello] Sent nonce: b'\x929\xf5\xd0\xd3\x1cx\x86s\xfd\xe6\x91(\x1f\xc7\xa7'
2025-06-08 12:51:54,323 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 12:51:54,323 [INFO] [server.py:<module>] Received nonce: b'\x929\xf5\xd0\xd3\x1cx\x86s\xfd\xe6\x91(\x1f\xc7\xa7'
2025-06-08 12:51:54,323 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 12:51:54,323 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:51:54,323 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:51:54,323 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:51:54,324 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 12:51:54,324 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 12:51:54,324 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 12:51:54,324 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 12:51:54,324 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 12:51:54,325 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 12:51:54,325 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 12:52:00,047 [ERROR] [ca_cert.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 0 bytes, expected 256 bytes.
2025-06-08 12:52:00,049 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 0 bytes, expected 256 bytes.
2025-06-08 12:52:00,050 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 169, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 87, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 0 bytes, expected 256 bytes.
2025-06-08 12:52:00,052 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:52:02,724 [INFO] [server.py:<module>] Server starting
2025-06-08 12:52:02,790 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:52:04,049 [INFO] [device.py:<module>] Device started
2025-06-08 12:52:04,116 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:52:04,116 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:52:04,116 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 58498)
2025-06-08 12:52:04,116 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:52:04,116 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:52:04,116 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:52:04,116 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:52:04,116 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:52:04,116 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:52:04,116 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:52:04,116 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:52:04,116 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:52:04,116 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:52:04,116 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:52:04,116 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:52:04,116 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:52:04,116 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:52:04,117 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:52:04,117 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:52:04,117 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:52:04,120 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:52:04,120 [INFO] [device.py:send_hello] Sent nonce: b'\xc0x(\x90tTM\x00\xdd\xdfnc\xf9a\xd4\xf6'
2025-06-08 12:52:04,120 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 12:52:04,120 [INFO] [server.py:<module>] Received nonce: b'\xc0x(\x90tTM\x00\xdd\xdfnc\xf9a\xd4\xf6'
2025-06-08 12:52:04,120 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 12:52:04,120 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:52:04,120 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:52:04,120 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:52:04,121 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 12:52:04,121 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 12:52:04,121 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 12:52:04,121 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 12:52:04,121 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 12:52:04,121 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 12:52:04,122 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 12:52:04,122 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 12:52:04,125 [ERROR] [ca_cert.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 80, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 12:52:04,125 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 80, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 12:52:04,126 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 80, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 169, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 87, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 12:52:04,126 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:52:04,127 [INFO] [device.py:recv_hello] Received nonce: b''
2025-06-08 12:52:04,127 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 12:52:04,127 [ERROR] [device.py:send_end_of_file] Failed to send end of file
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 97, in send_end_of_file
    client_socket.sendall(b"<ENDD>")
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-06-08 12:54:13,839 [INFO] [server.py:<module>] Server starting
2025-06-08 12:54:13,907 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:54:16,735 [INFO] [device.py:<module>] Device started
2025-06-08 12:54:16,802 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:54:16,803 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:54:16,802 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 58507)
2025-06-08 12:54:16,803 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:54:16,803 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:54:16,803 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:54:16,803 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:54:16,803 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:54:16,803 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:54:16,803 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:54:16,803 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:54:16,803 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:54:16,803 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:54:16,803 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:54:16,803 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:54:16,804 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:54:16,804 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:54:16,805 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:54:16,806 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:54:16,806 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:54:16,808 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:54:16,808 [INFO] [device.py:send_hello] Sent nonce: b'J\xaf\x8b\xac\xd0\xfd\xdc\x01\xa8U\xf1\xb3[\x06\x13\xb3'
2025-06-08 12:54:16,808 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 12:54:16,808 [INFO] [server.py:<module>] Received nonce: b'J\xaf\x8b\xac\xd0\xfd\xdc\x01\xa8U\xf1\xb3[\x06\x13\xb3'
2025-06-08 12:54:16,808 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 12:54:16,808 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:54:16,808 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:54:16,808 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:54:16,809 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 12:54:16,809 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 12:54:16,809 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 12:54:16,809 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 12:54:16,809 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 12:54:16,809 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 12:54:16,810 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 12:54:16,810 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 12:54:16,812 [ERROR] [ca_cert.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 80, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 12:54:16,813 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 80, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 12:54:16,814 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 80, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 169, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 87, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 12:54:16,816 [INFO] [server.py:<module>] Server shut down
2025-06-08 12:54:16,816 [INFO] [device.py:recv_hello] Received nonce: b''
2025-06-08 12:54:16,816 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 12:54:16,816 [ERROR] [device.py:send_end_of_file] Failed to send end of file
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 97, in send_end_of_file
    client_socket.sendall(b"<ENDD>")
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe
2025-06-08 12:58:59,994 [INFO] [server.py:<module>] Server starting
2025-06-08 12:59:00,061 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 12:59:02,811 [INFO] [device.py:<module>] Device started
2025-06-08 12:59:02,878 [INFO] [device.py:<module>] Connected to server
2025-06-08 12:59:02,878 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 12:59:02,878 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 58542)
2025-06-08 12:59:02,878 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 12:59:02,878 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 12:59:02,878 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 12:59:02,878 [INFO] [server.py:<module>] Expecting hello
2025-06-08 12:59:02,878 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 12:59:02,878 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 12:59:02,879 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:59:02,879 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:59:02,879 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 12:59:02,879 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 12:59:02,879 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 12:59:02,879 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 12:59:02,879 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 12:59:02,879 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 12:59:02,881 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 12:59:02,882 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 12:59:02,882 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 12:59:02,884 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:59:02,884 [INFO] [device.py:send_hello] Sent nonce: b'S \\\x1c\xf1\xcd\xe3\x91L\x0bx\x8e\x95J\xe1\xbf'
2025-06-08 12:59:02,884 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 12:59:02,884 [INFO] [server.py:<module>] Received nonce: b'S \\\x1c\xf1\xcd\xe3\x91L\x0bx\x8e\x95J\xe1\xbf'
2025-06-08 12:59:02,884 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 12:59:02,884 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 12:59:02,884 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 12:59:02,884 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 12:59:02,885 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 12:59:02,885 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 12:59:02,885 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 12:59:02,885 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 12:59:02,885 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 12:59:02,885 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 12:59:02,886 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 12:59:02,886 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 12:59:02,888 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 12:59:02,888 [INFO] [server.py:send_hello] Sent nonce: b'X$Z\xb8C(\x0e_u\x0f\x88\xafuR\xadn'
2025-06-08 12:59:02,888 [INFO] [device.py:recv_hello] Received nonce: b'X$Z\xb8C(\x0e_u\x0f\x88\xafuR\xadn'
2025-06-08 12:59:02,889 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 12:59:02,889 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 12:59:02,889 [INFO] [device.py:<module>] Device socket closed
2025-06-08 12:59:02,890 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 88, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 3: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 82, in send_hello
    ack_msg = decrypt_message(ack, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xb8 in position 3: invalid start byte
2025-06-08 12:59:02,891 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 88, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 3: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 169, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 87, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 82, in send_hello
    ack_msg = decrypt_message(ack, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 90, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xb8 in position 3: invalid start byte
2025-06-08 12:59:02,892 [INFO] [server.py:<module>] Server shut down
2025-06-08 13:18:14,859 [INFO] [server.py:<module>] Server starting
2025-06-08 13:18:14,927 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 13:18:16,668 [INFO] [device.py:<module>] Device started
2025-06-08 13:18:16,737 [INFO] [device.py:<module>] Connected to server
2025-06-08 13:18:16,737 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 13:18:16,737 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 58705)
2025-06-08 13:18:16,737 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:18:16,737 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:18:16,737 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 13:18:16,737 [INFO] [server.py:<module>] Expecting hello
2025-06-08 13:18:16,737 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 13:18:16,738 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 13:18:16,738 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 13:18:16,738 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 13:18:16,738 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 13:18:16,738 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 13:18:16,738 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 13:18:16,738 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 13:18:16,738 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 13:18:16,738 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 13:18:16,739 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 13:18:16,740 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 13:18:16,740 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 13:18:16,742 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 13:18:16,742 [INFO] [device.py:send_hello] Sent nonce: b'II\xbe\x19S\xc4\xde\xa7f\x9e\x83\xca\x92\x07\xf5\xbd'
2025-06-08 13:18:16,742 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 13:18:16,742 [INFO] [server.py:<module>] Received nonce: b'II\xbe\x19S\xc4\xde\xa7f\x9e\x83\xca\x92\x07\xf5\xbd'
2025-06-08 13:18:16,742 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 13:18:16,742 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 13:18:16,743 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 13:18:16,743 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 13:18:16,744 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 13:18:16,744 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 13:18:16,744 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 13:18:16,744 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 13:18:16,744 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 13:18:16,744 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 13:18:16,744 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 13:18:16,744 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 13:18:16,746 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 13:18:16,746 [INFO] [server.py:send_hello] Sent nonce: b'e\x9fo\\\xf1c\x03\xe3\xd2\xacC&\xd1<\xd0r'
2025-06-08 13:18:16,746 [INFO] [device.py:recv_hello] Received nonce: b'e\x9fo\\\xf1c\x03\xe3\xd2\xacC&\xd1<\xd0r'
2025-06-08 13:18:16,747 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 13:18:16,747 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 13:18:16,747 [INFO] [device.py:<module>] Device socket closed
2025-06-08 13:18:16,748 [INFO] [server.py:send_hello] Device acknowledgement: NONCE_RECEIVED
2025-06-08 13:18:16,748 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:18:16,748 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:18:16,748 [INFO] [server.py:<module>] Received header: b'<ENDD>'
2025-06-08 13:18:16,748 [INFO] [server.py:<module>] Received end of file
2025-06-08 13:18:16,749 [INFO] [server.py:<module>] Server closed
2025-06-08 13:18:16,749 [INFO] [server.py:<module>] Server shut down
2025-06-08 13:35:47,269 [INFO] [server.py:<module>] Server starting
2025-06-08 13:35:47,337 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 13:35:50,231 [INFO] [device.py:<module>] Device started
2025-06-08 13:35:50,298 [INFO] [device.py:<module>] Connected to server
2025-06-08 13:35:50,298 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 58920)
2025-06-08 13:35:50,298 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:35:50,302 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 13:35:50,302 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:35:50,302 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 13:35:50,302 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 13:35:50,302 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 13:35:50,302 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 13:35:50,305 [ERROR] [server.py:<module>] Failed to receive pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 91, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte
2025-06-08 13:35:50,306 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 182, in <module>
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 91, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xbb in position 0: invalid start byte
2025-06-08 13:35:50,306 [INFO] [server.py:<module>] Server shut down
2025-06-08 13:35:50,306 [ERROR] [device.py:send_pre_master_secret] Failed to send pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 168, in send_pre_master_secret
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 77, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 0 bytes, expected 256 bytes.
2025-06-08 13:40:50,937 [INFO] [server.py:<module>] Server starting
2025-06-08 13:40:51,005 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 13:40:52,732 [INFO] [device.py:<module>] Device started
2025-06-08 13:40:52,799 [INFO] [device.py:<module>] Connected to server
2025-06-08 13:40:52,799 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 58977)
2025-06-08 13:40:52,799 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:40:52,801 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 13:40:52,801 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:40:52,801 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 13:40:52,801 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 13:40:52,801 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 13:40:52,801 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 13:40:52,804 [ERROR] [server.py:<module>] Failed to receive pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 91, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xd1 in position 0: invalid continuation byte
2025-06-08 13:40:52,805 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 182, in <module>
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 91, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xd1 in position 0: invalid continuation byte
2025-06-08 13:40:52,806 [INFO] [server.py:<module>] Server shut down
2025-06-08 13:40:52,806 [ERROR] [device.py:send_pre_master_secret] Failed to send pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 168, in send_pre_master_secret
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 77, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 0 bytes, expected 256 bytes.
2025-06-08 13:43:45,737 [INFO] [server.py:<module>] Server starting
2025-06-08 13:43:45,805 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 13:43:47,463 [INFO] [device.py:<module>] Device started
2025-06-08 13:43:47,532 [INFO] [device.py:<module>] Connected to server
2025-06-08 13:43:47,532 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59000)
2025-06-08 13:43:47,532 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:43:47,535 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 13:43:47,535 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:43:47,535 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 13:43:47,536 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 13:43:47,536 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 13:43:47,536 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 13:43:47,539 [ERROR] [server.py:<module>] Failed to receive pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 91, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0x80 in position 3: invalid start byte
2025-06-08 13:43:47,540 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 3: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 182, in <module>
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 91, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0x80 in position 3: invalid start byte
2025-06-08 13:43:47,541 [INFO] [server.py:<module>] Server shut down
2025-06-08 13:43:47,541 [ERROR] [device.py:send_pre_master_secret] Failed to send pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 168, in send_pre_master_secret
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 77, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 0 bytes, expected 256 bytes.
2025-06-08 13:44:48,890 [INFO] [server.py:<module>] Server starting
2025-06-08 13:44:49,012 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 13:44:50,596 [INFO] [device.py:<module>] Device started
2025-06-08 13:44:50,663 [INFO] [device.py:<module>] Connected to server
2025-06-08 13:44:50,663 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59018)
2025-06-08 13:44:50,664 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:44:50,666 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 13:44:50,667 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:44:50,667 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 13:44:50,667 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 13:44:50,667 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 13:44:50,667 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 13:44:50,669 [ERROR] [server.py:<module>] Failed to receive pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 3: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 91, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xc8 in position 3: invalid continuation byte
2025-06-08 13:44:50,671 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    return decrypted.decode()
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 3: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 182, in <module>
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 91, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xc8 in position 3: invalid continuation byte
2025-06-08 13:44:50,671 [INFO] [server.py:<module>] Server shut down
2025-06-08 13:44:50,671 [INFO] [device.py:send_pre_master_secret] Received acknowledgement: b''
2025-06-08 13:44:50,672 [ERROR] [device.py:send_pre_master_secret] Failed to send pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 169, in send_pre_master_secret
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 77, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 0 bytes, expected 256 bytes.
2025-06-08 13:47:45,032 [INFO] [server.py:<module>] Server starting
2025-06-08 13:47:45,099 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 13:47:46,667 [INFO] [device.py:<module>] Device started
2025-06-08 13:47:46,735 [INFO] [device.py:<module>] Connected to server
2025-06-08 13:47:46,735 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59042)
2025-06-08 13:47:46,735 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:47:46,739 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 13:47:46,739 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:47:46,739 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 13:47:46,739 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 13:47:46,739 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 13:47:46,739 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 13:47:46,742 [ERROR] [server.py:<module>] Failed to receive pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 86, in decrypt_message
    return decrypted.decode() if decode else decrypted
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 88, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte
2025-06-08 13:47:46,743 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 86, in decrypt_message
    return decrypted.decode() if decode else decrypted
           ~~~~~~~~~~~~~~~~^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 182, in <module>
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 175, in <module>
    pre_master_secret = decrypt_message(encrypted_pre_master_secret, server_private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 88, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: 'utf-8' codec can't decode byte 0xce in position 0: invalid continuation byte
2025-06-08 13:47:46,743 [INFO] [server.py:<module>] Server shut down
2025-06-08 13:47:46,744 [INFO] [device.py:send_pre_master_secret] Received acknowledgement: b''
2025-06-08 13:47:46,744 [ERROR] [device.py:send_pre_master_secret] Failed to send pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 169, in send_pre_master_secret
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 75, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 0 bytes, expected 256 bytes.
2025-06-08 13:48:07,790 [INFO] [server.py:<module>] Server starting
2025-06-08 13:48:11,694 [INFO] [server.py:<module>] Server starting
2025-06-08 13:48:17,543 [INFO] [server.py:<module>] Server starting
2025-06-08 13:48:17,609 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 13:48:20,196 [INFO] [device.py:<module>] Device started
2025-06-08 13:48:20,263 [INFO] [device.py:<module>] Connected to server
2025-06-08 13:48:20,263 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59045)
2025-06-08 13:48:20,264 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:48:20,267 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 13:48:20,267 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:48:20,267 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 13:48:20,267 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 13:48:20,267 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 13:48:20,267 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 13:48:20,270 [INFO] [server.py:<module>] Received pre-master secret: b'I&t\xa5pV\x8a3\x9b\x1b\xae>mc\xdfB!Ez\xbc\xf7\x85\xa9\x9a1C`Z\x0c(\xb4\x1b'
2025-06-08 13:48:20,270 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 13:48:20,270 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:48:20,270 [INFO] [device.py:send_pre_master_secret] Received acknowledgement: b'\x8d\x0bg\x85\x1c,\x19\xff\x8c\xaa\xf0\xb2\x010<\xf9\x17\x12\xd9\xa9\x96\x1bK\xdbFl\xaa\x86\x98-\xfb\x03\xedd\xdd\x87\x01\x05\xeb\x12q\xf1\xc9{\xb9\x96\xafM\x06\xd0\x9d\xd5E\x8a\x87\'O\x9d+;\xa7\x82\xeb#\xf2j72\x7f\xf1\xef\x1aF\xf7\x18\x0c\xc2\xcd\xe5\x1d(A\xa1\xca\xb7\xe7\xf9\xbbVT\xe0\xd1\x07\x17\xaazW\xae"\xc9\x88\x0bj\xf6\xfe\xdaDei\tf\xea\xd5P\xbe\xb9J\x91x`\x0bV(\xfd\x8e\x9c\x1d|!\x8c\x9aeF\xfd\nu\xc1\x03\x1bYV.\x91\x1b\x04\x1d\xd0\xa0\xe4\xd9\x83/\xfd\xff\x7f\xb8\ri\xe7d/X6Vt\xc1\xda\x93\x0b\xc4\xf3\xf4":g9$8\xfd\xec\xf2vK\n\x814\x1c\x07p\x0cc\xed\xca\xe6\xbam\xf1Y$I\x8d\x85\xef\x1fV\n\x9e\x99\xbf\x92N.E\xd0H\x8fJ\xc3\xd8e<\x0c@\xed\xfe"\xdfLN\xd1\x91\x97\xf7 Q\xb9\xccGW\xce\xf1$\xb7yg\r/\x8aL\xeew\xcd\xc0W\x84\x95'
2025-06-08 13:48:20,273 [INFO] [device.py:send_pre_master_secret] Server acknowledgement: PREM_RECEIVED
2025-06-08 13:48:20,273 [INFO] [device.py:<module>] Device socket closed
2025-06-08 13:48:20,273 [WARNING] [server.py:recv_exact] Connection interrupted during receive
2025-06-08 13:48:20,273 [INFO] [server.py:recv_exact] Received 0 bytes successfully
2025-06-08 13:48:20,273 [INFO] [server.py:<module>] Received header: b''
2025-06-08 13:48:20,273 [ERROR] [server.py:<module>] Invalid header received
2025-06-08 13:48:20,273 [INFO] [server.py:<module>] Server shut down
2025-06-08 13:49:05,663 [INFO] [server.py:<module>] Server starting
2025-06-08 13:49:05,731 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 13:49:07,322 [INFO] [device.py:<module>] Device started
2025-06-08 13:49:07,389 [INFO] [device.py:<module>] Connected to server
2025-06-08 13:49:07,390 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59054)
2025-06-08 13:49:07,390 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:49:07,393 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 13:49:07,393 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:49:07,393 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 13:49:07,393 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 13:49:07,393 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 13:49:07,393 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 13:49:07,396 [INFO] [server.py:<module>] Received pre-master secret: b'\xb2e\xeb\xcdg/\xc2\xddM\\\xc3\xe6\x04\x0fbL\xd3\xe6\xee\xb4\x97$\t\xbb\x88\xa9\x1f\xa6\xec\x85%\xce'
2025-06-08 13:49:07,396 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 13:49:07,396 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:49:07,399 [INFO] [device.py:send_pre_master_secret] Server acknowledgement: PREM_RECEIVED
2025-06-08 13:49:07,399 [INFO] [device.py:<module>] Device socket closed
2025-06-08 13:49:07,399 [WARNING] [server.py:recv_exact] Connection interrupted during receive
2025-06-08 13:49:07,399 [INFO] [server.py:recv_exact] Received 0 bytes successfully
2025-06-08 13:49:07,399 [INFO] [server.py:<module>] Received header: b''
2025-06-08 13:49:07,399 [ERROR] [server.py:<module>] Invalid header received
2025-06-08 13:49:07,399 [INFO] [server.py:<module>] Server shut down
2025-06-08 13:49:21,813 [INFO] [device.py:<module>] Device started
2025-06-08 13:49:21,880 [ERROR] [device.py:<module>] Failed to connect to server
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 18, in <module>
    client.connect(("localhost", 9999))
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
ConnectionRefusedError: [Errno 61] Connection refused
2025-06-08 13:49:23,432 [INFO] [server.py:<module>] Server starting
2025-06-08 13:49:23,501 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 13:49:25,135 [INFO] [device.py:<module>] Device started
2025-06-08 13:49:25,202 [INFO] [device.py:<module>] Connected to server
2025-06-08 13:49:25,202 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59062)
2025-06-08 13:49:25,203 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:49:25,205 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 13:49:25,205 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:49:25,205 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 13:49:25,205 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 13:49:25,205 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 13:49:25,205 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 13:49:25,207 [INFO] [server.py:<module>] Received pre-master secret: b']rLJg\xc3\xa7\xe4e\x84.\xbe\xd6X\xf1%\xd6u\x08P#\xbb\x06\x7fB\xe3i>N\xcb\x1a\x81'
2025-06-08 13:49:25,208 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 13:49:25,208 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 13:49:25,210 [INFO] [device.py:send_pre_master_secret] Server acknowledgement: PREM_RECEIVED
2025-06-08 13:49:25,210 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 13:49:25,211 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 13:49:25,211 [INFO] [server.py:<module>] Received header: b'<ENDD>'
2025-06-08 13:49:25,211 [INFO] [device.py:<module>] Device socket closed
2025-06-08 13:49:25,211 [INFO] [server.py:<module>] Received end of file
2025-06-08 13:49:25,211 [INFO] [server.py:<module>] Server closed
2025-06-08 13:49:25,211 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:24:03,610 [INFO] [server.py:<module>] Server starting
2025-06-08 14:24:03,679 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:24:05,534 [INFO] [device.py:<module>] Device started
2025-06-08 14:24:05,601 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:24:05,601 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:24:05,601 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59358)
2025-06-08 14:24:05,601 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:24:05,601 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:24:05,601 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:24:05,601 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:24:05,601 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:24:05,601 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:24:05,602 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:24:05,602 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:24:05,602 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:24:05,602 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:24:05,602 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:24:05,602 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:24:05,602 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:24:05,602 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:24:05,605 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:24:05,606 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:24:05,606 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:24:05,607 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:24:05,608 [INFO] [device.py:send_hello] Sent nonce: b'\xbfI\xf6I\x08\x83\xc3\x19[8\xa2gg]A\xd2'
2025-06-08 14:24:05,608 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:24:05,608 [INFO] [server.py:<module>] Received nonce: b'\xbfI\xf6I\x08\x83\xc3\x19[8\xa2gg]A\xd2'
2025-06-08 14:24:05,608 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:24:05,608 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:24:05,608 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:24:05,609 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:24:05,609 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:24:05,610 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 14:24:05,610 [ERROR] [ca_cert.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 14:24:05,611 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 14:24:05,611 [ERROR] [device.py:send_pre_master_secret] Failed to send pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 79, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 171, in send_pre_master_secret
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 14:24:05,611 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 169, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 87, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 14:24:05,612 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:24:05,611 [ERROR] [device.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 79, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 118, in send_hello
    pre_master_secret = send_pre_master_secret(client_socket, server_public_key)
  File "/Users/omerfarukbulut/info_sec/device.py", line 176, in send_pre_master_secret
    raise e
  File "/Users/omerfarukbulut/info_sec/device.py", line 171, in send_pre_master_secret
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 14:26:33,593 [INFO] [server.py:<module>] Server starting
2025-06-08 14:26:33,661 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:26:35,176 [INFO] [device.py:<module>] Device started
2025-06-08 14:26:35,243 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:26:35,243 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:26:35,243 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59384)
2025-06-08 14:26:35,243 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:26:35,243 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:26:35,243 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:26:35,243 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:26:35,244 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:26:35,244 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:26:35,244 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:26:35,245 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:26:35,245 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:26:35,245 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:26:35,245 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:26:35,245 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:26:35,245 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:26:35,245 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:26:35,248 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:26:35,249 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:26:35,249 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:26:35,251 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:26:35,251 [INFO] [device.py:send_hello] Sent nonce: b'\x96{ \x0f\xf6 V\xdc=}#\xf5\xd6\xf7m\x1a'
2025-06-08 14:26:35,251 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:26:35,251 [INFO] [server.py:<module>] Received nonce: b'\x96{ \x0f\xf6 V\xdc=}#\xf5\xd6\xf7m\x1a'
2025-06-08 14:26:35,251 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:26:35,251 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:26:35,252 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:26:35,252 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:26:35,252 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:26:35,253 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 14:26:35,253 [ERROR] [ca_cert.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 14:26:35,254 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 14:26:35,254 [ERROR] [device.py:send_pre_master_secret] Failed to send pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 79, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 171, in send_pre_master_secret
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 14:26:35,254 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 165, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 87, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 24, in send_certificate
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 76, in decrypt_message
    raise ValueError(f"Encrypted message length is invalid. Got {len(encrypted_message)} bytes, expected 256 bytes.")
ValueError: Encrypted message length is invalid. Got 6 bytes, expected 256 bytes.
2025-06-08 14:26:35,255 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:26:35,255 [ERROR] [device.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 79, in decrypt_message
    decrypted = private_key.decrypt(
        encrypted_message,
    ...<4 lines>...
        )
    )
ValueError: Decryption failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 118, in send_hello
    pre_master_secret = send_pre_master_secret(client_socket, server_public_key)
  File "/Users/omerfarukbulut/info_sec/device.py", line 176, in send_pre_master_secret
    raise e
  File "/Users/omerfarukbulut/info_sec/device.py", line 171, in send_pre_master_secret
    ack_msg = decrypt_message(ack, private_key)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 89, in decrypt_message
    raise ValueError(f"Decryption failed: {e}")
ValueError: Decryption failed: Decryption failed
2025-06-08 14:30:39,988 [INFO] [server.py:<module>] Server starting
2025-06-08 14:30:40,057 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:30:41,800 [INFO] [device.py:<module>] Device started
2025-06-08 14:30:41,867 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:30:41,867 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:30:41,867 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59412)
2025-06-08 14:30:41,867 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:30:41,867 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:30:41,867 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:30:41,867 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:30:41,867 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:30:41,867 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:30:41,868 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:30:41,868 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:30:41,868 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:30:41,868 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:30:41,868 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:30:41,868 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:30:41,868 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:30:41,868 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:30:41,871 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:30:41,872 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:30:41,872 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:30:41,874 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:30:41,874 [INFO] [device.py:send_hello] Sent nonce: b'\xd5\x82\xb8&\x04V\xc2\x0152\xff\r\xc20\x11\xf0'
2025-06-08 14:30:41,874 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:30:41,874 [INFO] [server.py:<module>] Received nonce: b'\xd5\x82\xb8&\x04V\xc2\x0152\xff\r\xc20\x11\xf0'
2025-06-08 14:30:41,874 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:30:41,874 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:30:41,875 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:30:41,875 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:30:41,876 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:30:41,880 [ERROR] [ca_cert.py:send_certificate] Failed to send certificate
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 23, in send_certificate
    ack = client_socket.recv(256)
ConnectionResetError: [Errno 54] Connection reset by peer
2025-06-08 14:30:41,881 [ERROR] [server.py:send_hello] Failed to send hello
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 23, in send_certificate
    ack = client_socket.recv(256)
ConnectionResetError: [Errno 54] Connection reset by peer
2025-06-08 14:30:41,881 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 165, in <module>
    send_hello(client)
    ~~~~~~~~~~^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/server.py", line 87, in send_hello
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 76, in send_hello
    send_certificate(client_socket, "certificates/server_certificate.json", private_key=server_private_key)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 28, in send_certificate
    raise e
  File "/Users/omerfarukbulut/info_sec/ca_cert.py", line 23, in send_certificate
    ack = client_socket.recv(256)
ConnectionResetError: [Errno 54] Connection reset by peer
2025-06-08 14:30:41,881 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:30:55,239 [INFO] [server.py:<module>] Server starting
2025-06-08 14:30:55,307 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:30:57,091 [INFO] [device.py:<module>] Device started
2025-06-08 14:30:57,157 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:30:57,157 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59419)
2025-06-08 14:30:57,157 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:30:57,158 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:30:57,158 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:30:57,158 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:30:57,158 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:30:57,158 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:30:57,158 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:30:57,158 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:30:57,158 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:30:57,158 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:30:57,158 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:30:57,158 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:30:57,158 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:30:57,158 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:30:57,159 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:30:57,160 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:30:57,161 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:30:57,161 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:30:57,163 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:30:57,163 [INFO] [device.py:send_hello] Sent nonce: b'\x92\xba\x11\x8c\x8c\xad\xd0OfHt\xd5\x18\x0f/\x93'
2025-06-08 14:30:57,163 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:30:57,163 [INFO] [server.py:<module>] Received nonce: b'\x92\xba\x11\x8c\x8c\xad\xd0OfHt\xd5\x18\x0f/\x93'
2025-06-08 14:30:57,163 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:30:57,163 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:30:57,164 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:30:57,164 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:30:57,164 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:30:57,164 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 14:30:57,165 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 14:30:57,165 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 14:30:57,165 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 14:30:57,165 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:30:57,165 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 14:30:57,165 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 14:30:57,167 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:30:57,167 [INFO] [server.py:send_hello] Sent nonce: b'\xa9x\x1d\x1ft>=r\xd5\x80\x16\x9d\xd6C\xc1\xb2'
2025-06-08 14:30:57,167 [INFO] [device.py:recv_hello] Received nonce: b'\xa9x\x1d\x1ft>=r\xd5\x80\x16\x9d\xd6C\xc1\xb2'
2025-06-08 14:30:57,167 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:30:57,167 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 14:30:57,168 [INFO] [server.py:send_hello] Device acknowledgement: NONCE_RECEIVED
2025-06-08 14:30:57,168 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:30:57,168 [ERROR] [device.py:send_pre_master_secret] Failed to send pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 169, in send_pre_master_secret
    ack = client_socket.recv(256)
ConnectionResetError: [Errno 54] Connection reset by peer
2025-06-08 14:32:36,835 [INFO] [server.py:<module>] Server starting
2025-06-08 14:32:36,903 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:32:39,016 [INFO] [device.py:<module>] Device started
2025-06-08 14:32:39,084 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:32:39,084 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59428)
2025-06-08 14:32:39,084 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:32:39,084 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:32:39,084 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:32:39,084 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:32:39,084 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:32:39,084 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:32:39,084 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:32:39,085 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:32:39,085 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:32:39,085 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:32:39,085 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:32:39,085 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:32:39,085 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:32:39,085 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:32:39,086 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:32:39,087 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:32:39,088 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:32:39,088 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:32:39,090 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:32:39,090 [INFO] [device.py:send_hello] Sent nonce: b'\xb8\xb8\x054r*\x13S\xe6\xe6:\x15\xf7\x05\xa9\xe6'
2025-06-08 14:32:39,090 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:32:39,090 [INFO] [server.py:<module>] Received nonce: b'\xb8\xb8\x054r*\x13S\xe6\xe6:\x15\xf7\x05\xa9\xe6'
2025-06-08 14:32:39,090 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:32:39,090 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:32:39,091 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:32:39,091 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:32:39,091 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:32:39,091 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 14:32:39,091 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 14:32:39,091 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 14:32:39,091 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 14:32:39,092 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:32:39,092 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 14:32:39,092 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 14:32:39,094 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:32:39,094 [INFO] [server.py:send_hello] Sent nonce: b'\xd6=\x93\xa0\xce\x93\xd5R\x93\xb5\xe4\x8d\xb2\xc2p5'
2025-06-08 14:32:39,094 [INFO] [device.py:recv_hello] Received nonce: b'\xd6=\x93\xa0\xce\x93\xd5R\x93\xb5\xe4\x8d\xb2\xc2p5'
2025-06-08 14:32:39,095 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:32:39,095 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 14:32:39,096 [INFO] [server.py:send_hello] Device acknowledgement: NONCE_RECEIVED
2025-06-08 14:32:39,096 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:32:39,096 [ERROR] [device.py:send_pre_master_secret] Failed to send pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/device.py", line 169, in send_pre_master_secret
    ack = client_socket.recv(256)
ConnectionResetError: [Errno 54] Connection reset by peer
2025-06-08 14:34:29,551 [INFO] [server.py:<module>] Server starting
2025-06-08 14:34:29,619 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:34:31,423 [INFO] [device.py:<module>] Device started
2025-06-08 14:34:31,489 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:34:31,489 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:34:31,489 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59440)
2025-06-08 14:34:31,490 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:34:31,490 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:34:31,490 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:34:31,490 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:34:31,490 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:34:31,490 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:34:31,490 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:34:31,490 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:34:31,490 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:34:31,490 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:34:31,490 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:34:31,490 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:34:31,490 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:34:31,490 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:34:31,493 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:34:31,494 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:34:31,494 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:34:31,496 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:34:31,496 [INFO] [device.py:send_hello] Sent nonce: b'H\x9b)*\xdc\x0f\x83\x06\xbf\xcb\x18H$#]D'
2025-06-08 14:34:31,496 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:34:31,496 [INFO] [server.py:<module>] Received nonce: b'H\x9b)*\xdc\x0f\x83\x06\xbf\xcb\x18H$#]D'
2025-06-08 14:34:31,496 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:34:31,496 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:34:31,497 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:34:31,497 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:34:31,498 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:34:31,498 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 14:34:31,498 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 14:34:31,498 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 14:34:31,498 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 14:34:31,498 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:34:31,499 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 14:34:31,499 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 14:34:31,501 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:34:31,501 [INFO] [server.py:send_hello] Sent nonce: b',H\x01\xe9\xe1\xb6\xe0.\x0e\x1b\xdfU3\xf4:\xf0'
2025-06-08 14:34:31,501 [INFO] [device.py:recv_hello] Received nonce: b',H\x01\xe9\xe1\xb6\xe0.\x0e\x1b\xdfU3\xf4:\xf0'
2025-06-08 14:34:31,501 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:34:31,502 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 14:34:31,502 [INFO] [server.py:send_hello] Device acknowledgement: NONCE_RECEIVED
2025-06-08 14:34:31,502 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:34:31,502 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:34:31,502 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 14:34:31,502 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 14:34:31,502 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 14:34:31,502 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 14:34:31,504 [INFO] [server.py:<module>] Received pre-master secret: b'\xe9\x07$\x03\xf5\xad\x8ciG\xe3\x8c\xdf\xfft\x1c\x8f\xe9\xcd\x9c\xa5\x97T\x94\xb5\x9c\x10I\x88N\r]\x9f'
2025-06-08 14:34:31,504 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:34:31,504 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:34:31,505 [INFO] [device.py:send_pre_master_secret] Server acknowledgement: PREM_RECEIVED
2025-06-08 14:34:31,505 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 14:34:31,505 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:34:31,505 [INFO] [server.py:<module>] Received header: b'<ENDD>'
2025-06-08 14:34:31,505 [INFO] [server.py:<module>] Received end of file
2025-06-08 14:34:31,505 [INFO] [server.py:<module>] Server closed
2025-06-08 14:34:31,505 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:34:31,505 [INFO] [device.py:<module>] Derived keys: {'client_enc_key': b'\xc9[\x86}\xbek\xc3Y"DA\xc4{\xec\xf80', 'server_enc_key': b'\xde\xf5/\x96R\xa5`$\rI\xb8\xd1+\x0eHT', 'client_mac_key': b'\x01\nZ#\xe4\xdf\x0c\xf9\xe9\xe2\xb3\x05\x8f\xfb\xfe1', 'server_mac_key': b'\x98A\xde\xb6\xbc\xcc\xb9\x1a\xc7\x9cF4\xeb\xda4?', 'iv': b'\xd42-S+\xfa\x03x\x1c\x93K\xdcP$F\x1a'}
2025-06-08 14:34:31,505 [INFO] [device.py:<module>] Device socket closed
2025-06-08 14:40:11,148 [INFO] [server.py:<module>] Server starting
2025-06-08 14:40:11,217 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:40:13,541 [INFO] [device.py:<module>] Device started
2025-06-08 14:40:13,608 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:40:13,608 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:40:13,608 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59487)
2025-06-08 14:40:13,608 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:40:13,608 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:40:13,608 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:40:13,608 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:40:13,608 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:40:13,608 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:40:13,608 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:40:13,608 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:40:13,608 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:40:13,609 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:40:13,609 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:40:13,609 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:40:13,609 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:40:13,609 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:40:13,612 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:40:13,614 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:40:13,614 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:40:13,615 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:40:13,615 [INFO] [device.py:send_hello] Sent nonce: b'\xd4\xfa\xb2\x0e\xa7\xc5\x8b\xe7\x9b\xa3\xe1\xb7\xc3RYm'
2025-06-08 14:40:13,615 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:40:13,615 [INFO] [server.py:<module>] Received nonce: b'\xd4\xfa\xb2\x0e\xa7\xc5\x8b\xe7\x9b\xa3\xe1\xb7\xc3RYm'
2025-06-08 14:40:13,615 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:40:13,615 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:40:13,616 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:40:13,616 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:40:13,616 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:40:13,616 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 14:40:13,616 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 14:40:13,616 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 14:40:13,616 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 14:40:13,617 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:40:13,617 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 14:40:13,617 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 14:40:13,619 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:40:13,619 [INFO] [server.py:send_hello] Sent nonce: b'\xc3\xc2\xc4\x81\xe1\xf93\x1d\xddM\xb8\x80\x8d\x1f\xc7\xbb'
2025-06-08 14:40:13,619 [INFO] [device.py:recv_hello] Received nonce: b'\xc3\xc2\xc4\x81\xe1\xf93\x1d\xddM\xb8\x80\x8d\x1f\xc7\xbb'
2025-06-08 14:40:13,619 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:40:13,619 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 14:40:13,620 [INFO] [server.py:send_hello] Device acknowledgement: NONCE_RECEIVED
2025-06-08 14:40:13,620 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:40:13,620 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:40:13,620 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 14:40:13,620 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 14:40:13,620 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 14:40:13,620 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 14:40:13,622 [INFO] [server.py:<module>] Received pre-master secret: b'\x15\xbb$\x9e)\xe06\xdb\xff\x8e\xdb\xdd\xf7\x05\xfd\xdf\xe7Rv\xb1\xad\xde\x8e\xd6\x8c6qh\xdb\x1f\x16['
2025-06-08 14:40:13,622 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:40:13,622 [ERROR] [server.py:<module>] Failed to receive pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 183, in <module>
    DERIVED_KEYS = derive_keys(MASTER_SECRET, NONCE_DEVICE, NONCE_SERVER)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 93, in derive_keys
    seed = nonce1 + nonce2
           ~~~~~~~^~~~~~~~
TypeError: can't concat NoneType to bytes
2025-06-08 14:40:13,623 [INFO] [device.py:send_pre_master_secret] Server acknowledgement: PREM_RECEIVED
2025-06-08 14:40:13,623 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 14:40:13,623 [INFO] [device.py:<module>] Derived keys: {'client_enc_key': b'\x80\xb1\xdc/\xa3\x8b\xaa\x10\x00\x17,\xec\x11\xab\xbc\xb3', 'server_enc_key': b'\xae\x15\xacO*\xc4\xe6\x19a]\xe8\xea\x93!j\xbc', 'client_mac_key': b'\x99\xba\xdc\xea_I\xd4H\xa2b\x11\x01\x12\xaa\xb6\x13', 'server_mac_key': b'\x82\xa8l\xf7\x96\x9f\x13\xb2g\xe20\x14\xdan\xd9\xce', 'iv': b'\xea\xbc\xbe%\xe8\xbe\x8f\x9d\xee\x9a\x0c\xc0\xa20L\x81'}
2025-06-08 14:40:13,623 [INFO] [device.py:<module>] Device socket closed
2025-06-08 14:40:13,623 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 187, in <module>
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 183, in <module>
    DERIVED_KEYS = derive_keys(MASTER_SECRET, NONCE_DEVICE, NONCE_SERVER)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 93, in derive_keys
    seed = nonce1 + nonce2
           ~~~~~~~^~~~~~~~
TypeError: can't concat NoneType to bytes
2025-06-08 14:40:13,623 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:42:12,908 [INFO] [server.py:<module>] Server starting
2025-06-08 14:42:12,978 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:42:15,107 [INFO] [device.py:<module>] Device started
2025-06-08 14:42:15,175 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:42:15,175 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:42:15,175 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59506)
2025-06-08 14:42:15,175 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:42:15,175 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:42:15,175 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:42:15,175 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:42:15,175 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:42:15,175 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:42:15,175 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:42:15,175 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:42:15,175 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:42:15,175 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:42:15,175 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:42:15,176 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:42:15,176 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:42:15,176 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:42:15,178 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:42:15,180 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:42:15,180 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:42:15,181 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:42:15,181 [INFO] [device.py:send_hello] Sent nonce: b'Y\x1b\xea\xa4rlZ \x1c@D\x15\xfd\xd7.\x95'
2025-06-08 14:42:15,181 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:42:15,181 [INFO] [server.py:<module>] Received nonce: b'Y\x1b\xea\xa4rlZ \x1c@D\x15\xfd\xd7.\x95'
2025-06-08 14:42:15,181 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:42:15,181 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:42:15,182 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:42:15,182 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:42:15,183 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:42:15,183 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 14:42:15,183 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 14:42:15,183 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 14:42:15,183 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 14:42:15,183 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:42:15,184 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 14:42:15,184 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 14:42:15,186 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:42:15,186 [INFO] [server.py:send_hello] Sent nonce: b'\x01=D\x19\xect\xf4]\x00lo\xa2Ye\x89\x1e'
2025-06-08 14:42:15,186 [INFO] [device.py:recv_hello] Received nonce: b'\x01=D\x19\xect\xf4]\x00lo\xa2Ye\x89\x1e'
2025-06-08 14:42:15,186 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:42:15,187 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 14:42:15,187 [INFO] [server.py:send_hello] Device acknowledgement: NONCE_RECEIVED
2025-06-08 14:42:15,187 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:42:15,187 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:42:15,187 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 14:42:15,187 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 14:42:15,188 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 14:42:15,188 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 14:42:15,189 [INFO] [server.py:<module>] Received pre-master secret: b'?\xdd\xf8\xa7\x0c\xf3\x97E\x05\x9f\xd5e\xecX\xac/h-\xab)\xe4uf\x0b\xdbY\xe1\x00\x81\xe7\xff\xf6'
2025-06-08 14:42:15,189 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:42:15,189 [INFO] [server.py:<module>] Nonce device: b'Y\x1b\xea\xa4rlZ \x1c@D\x15\xfd\xd7.\x95'
2025-06-08 14:42:15,189 [INFO] [server.py:<module>] Nonce server: None
2025-06-08 14:42:15,190 [INFO] [device.py:send_pre_master_secret] Server acknowledgement: PREM_RECEIVED
2025-06-08 14:42:15,189 [ERROR] [server.py:<module>] Failed to receive pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 185, in <module>
    DERIVED_KEYS = derive_keys(MASTER_SECRET, NONCE_DEVICE, NONCE_SERVER)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 93, in derive_keys
    seed = nonce1 + nonce2
           ~~~~~~~^~~~~~~~
TypeError: can't concat NoneType to bytes
2025-06-08 14:42:15,190 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 14:42:15,190 [INFO] [device.py:<module>] Derived keys: {'client_enc_key': b'{\xe9e\x01\xf2\xdd~\xe0N!\xd2\x9a\x01\xae\xaa\xc9', 'server_enc_key': b'\xf3v\xdc\x8d)#\xff\x1d\x12(\xc0\xac=\x9f\xda\xdd', 'client_mac_key': b'\xd2\x8f\x13 \x0f\xc0\xbe\xfe[v\x86"\x08\x1b\x12Z', 'server_mac_key': b'^\x0c\x94\x97\xd3K\x0b\xf9\x99\x1e\xf4\x8a\x07\xd9\x9b\x92', 'iv': b'\xdf\x9e\x8a\xdd\xd8\xec3\xf0\xcan^R\xe7J\xc9\xa3'}
2025-06-08 14:42:15,190 [INFO] [device.py:<module>] Device socket closed
2025-06-08 14:42:15,190 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 189, in <module>
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 185, in <module>
    DERIVED_KEYS = derive_keys(MASTER_SECRET, NONCE_DEVICE, NONCE_SERVER)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 93, in derive_keys
    seed = nonce1 + nonce2
           ~~~~~~~^~~~~~~~
TypeError: can't concat NoneType to bytes
2025-06-08 14:42:15,191 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:42:45,743 [INFO] [server.py:<module>] Server starting
2025-06-08 14:42:45,824 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:42:47,499 [INFO] [device.py:<module>] Device started
2025-06-08 14:42:47,567 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:42:47,567 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59513)
2025-06-08 14:42:47,567 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:42:47,567 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:42:47,567 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:42:47,567 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:42:47,567 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:42:47,567 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:42:47,567 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:42:47,567 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:42:47,567 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:42:47,567 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:42:47,567 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:42:47,567 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:42:47,567 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:42:47,568 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:42:47,568 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:42:47,570 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:42:47,571 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:42:47,571 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:42:47,573 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:42:47,573 [INFO] [device.py:send_hello] Sent nonce: b"\x92\xda\x0b\xa7C\x07'\x81Z(\x1aa\x9e\x8b\xd3i"
2025-06-08 14:42:47,574 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:42:47,574 [INFO] [server.py:<module>] Received nonce: b"\x92\xda\x0b\xa7C\x07'\x81Z(\x1aa\x9e\x8b\xd3i"
2025-06-08 14:42:47,574 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:42:47,574 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:42:47,574 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:42:47,574 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:42:47,575 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:42:47,575 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 14:42:47,575 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 14:42:47,575 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 14:42:47,575 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 14:42:47,575 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:42:47,576 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 14:42:47,576 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 14:42:47,578 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:42:47,578 [INFO] [server.py:send_hello] Sent nonce: b'U\x1f$\x17e\x92\xadi \x817$\x82\xcf\x8fI'
2025-06-08 14:42:47,578 [INFO] [device.py:recv_hello] Received nonce: b'U\x1f$\x17e\x92\xadi \x817$\x82\xcf\x8fI'
2025-06-08 14:42:47,578 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:42:47,579 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 14:42:47,579 [INFO] [server.py:send_hello] Device acknowledgement: NONCE_RECEIVED
2025-06-08 14:42:47,579 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:42:47,579 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:42:47,579 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 14:42:47,579 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 14:42:47,579 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 14:42:47,579 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 14:42:47,581 [INFO] [server.py:<module>] Received pre-master secret: b'r\xc4\xc9o\xfb\xa6\xf6\xfe\x81\xbai\xf9\xecIMUP\xba\x8f\xf5\xa1\xd5\xc1p\x92\x80\xa1\xde0j\xcde'
2025-06-08 14:42:47,581 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:42:47,581 [INFO] [server.py:<module>] Nonce device: b"\x92\xda\x0b\xa7C\x07'\x81Z(\x1aa\x9e\x8b\xd3i"
2025-06-08 14:42:47,581 [INFO] [server.py:<module>] Nonce server: None
2025-06-08 14:42:47,582 [INFO] [device.py:send_pre_master_secret] Server acknowledgement: PREM_RECEIVED
2025-06-08 14:42:47,582 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 14:42:47,581 [ERROR] [server.py:<module>] Failed to receive pre-master secret
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 185, in <module>
    DERIVED_KEYS = derive_keys(MASTER_SECRET, NONCE_DEVICE, NONCE_SERVER)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 93, in derive_keys
    seed = nonce1 + nonce2
           ~~~~~~~^~~~~~~~
TypeError: can't concat NoneType to bytes
2025-06-08 14:42:47,582 [ERROR] [server.py:<module>] An error occurred during communication.
Traceback (most recent call last):
  File "/Users/omerfarukbulut/info_sec/server.py", line 189, in <module>
    raise e
  File "/Users/omerfarukbulut/info_sec/server.py", line 185, in <module>
    DERIVED_KEYS = derive_keys(MASTER_SECRET, NONCE_DEVICE, NONCE_SERVER)
  File "/Users/omerfarukbulut/info_sec/rsa_keys.py", line 93, in derive_keys
    seed = nonce1 + nonce2
           ~~~~~~~^~~~~~~~
TypeError: can't concat NoneType to bytes
2025-06-08 14:42:47,582 [INFO] [server.py:<module>] Server shut down
2025-06-08 14:42:47,582 [INFO] [device.py:<module>] Derived keys: {'client_enc_key': b'\xb1`\xd3\xc9\xa9\xe0\xfd\xd4\xd0\x97\xd6\xf1\xb1*\x00\x8f', 'server_enc_key': b'\x1c|\xd13kk\xff\x8b8b\x90t\x08:\xf4\x1e', 'client_mac_key': b'\x1b\xccv\xdc\x88\xdf&\x95L1\xdeD7\x0c\x9ds', 'server_mac_key': b'\x80\xdd\xbeZO\xfc\th\xc14\x16\xb5\xcd\x8e\xa2\xaa', 'iv': b'\x08Z\xe9\x01\x0e\xbbi\x87\x8c\xd7\xbaX\xdd\xb7\x1f\xbb'}
2025-06-08 14:42:47,582 [INFO] [device.py:<module>] Device socket closed
2025-06-08 14:44:45,858 [INFO] [server.py:<module>] Server starting
2025-06-08 14:44:45,926 [INFO] [server.py:<module>] Server listening on port 9999
2025-06-08 14:44:48,561 [INFO] [device.py:<module>] Device started
2025-06-08 14:44:48,629 [INFO] [device.py:<module>] Connected to server
2025-06-08 14:44:48,629 [INFO] [device.py:send_hello] Sent header: HELLO
2025-06-08 14:44:48,629 [INFO] [server.py:<module>] Accepted connection from ('127.0.0.1', 59530)
2025-06-08 14:44:48,629 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:44:48,629 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:44:48,629 [INFO] [server.py:<module>] Received header: b'<HELO>'
2025-06-08 14:44:48,629 [INFO] [server.py:<module>] Expecting hello
2025-06-08 14:44:48,629 [INFO] [server.py:recv_certificate] Receiving certificate header (length)...
2025-06-08 14:44:48,629 [INFO] [server.py:recv_exact] Receiving exactly 4 bytes...
2025-06-08 14:44:48,630 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:44:48,630 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:44:48,630 [INFO] [server.py:recv_exact] Received 4 bytes successfully
2025-06-08 14:44:48,630 [INFO] [server.py:recv_certificate] Length bytes (raw): 00000371
2025-06-08 14:44:48,630 [INFO] [server.py:recv_certificate] Expecting certificate of 881 bytes
2025-06-08 14:44:48,630 [INFO] [server.py:recv_exact] Receiving exactly 881 bytes...
2025-06-08 14:44:48,630 [INFO] [server.py:recv_exact] Received 881 bytes successfully
2025-06-08 14:44:48,630 [INFO] [server.py:recv_certificate] Received certificate from client
2025-06-08 14:44:48,633 [INFO] [server.py:recv_certificate] Sent acknowledgement
2025-06-08 14:44:48,635 [INFO] [server.py:<module>] Certificate validated successfully
2025-06-08 14:44:48,635 [INFO] [server.py:recv_exact] Receiving exactly 16 bytes...
2025-06-08 14:44:48,636 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:44:48,636 [INFO] [device.py:send_hello] Sent nonce: b'\x88!\x8cz\xd7c\x84:\xc9%\x00\x9e\x94\x14\x11\x18'
2025-06-08 14:44:48,636 [INFO] [server.py:recv_exact] Received 16 bytes successfully
2025-06-08 14:44:48,636 [INFO] [server.py:<module>] Received nonce: b'\x88!\x8cz\xd7c\x84:\xc9%\x00\x9e\x94\x14\x11\x18'
2025-06-08 14:44:48,637 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:44:48,637 [INFO] [server.py:send_hello] Sent header: HELLO
2025-06-08 14:44:48,637 [INFO] [ca_cert.py:send_certificate] Sent certificate length: 881
2025-06-08 14:44:48,637 [INFO] [ca_cert.py:send_certificate] Sent certificate
2025-06-08 14:44:48,638 [INFO] [device.py:send_hello] Server acknowledgement: HELLO_RECEIVED
2025-06-08 14:44:48,638 [INFO] [device.py:recv_hello] Received header: HELLO
2025-06-08 14:44:48,638 [INFO] [device.py:recv_hello] Recieving server certificate length..
2025-06-08 14:44:48,638 [INFO] [device.py:recv_hello] Expecting server cert length 881 bytes.
2025-06-08 14:44:48,638 [INFO] [device.py:recv_hello] Received server certificate: 
2025-06-08 14:44:48,638 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:44:48,639 [INFO] [device.py:recv_hello] Server certificate validated successfully
2025-06-08 14:44:48,639 [INFO] [device.py:recv_hello] Recieving server nonce..
2025-06-08 14:44:48,641 [INFO] [ca_cert.py:send_certificate] Server acknowledgement: CERT_RECEIVED
2025-06-08 14:44:48,642 [INFO] [server.py:send_hello] Sent nonce: b'\x93r\x15\xb3.\xf8E\xc8\xec\x8bM\x9a\x80\xdf]\xb1'
2025-06-08 14:44:48,642 [INFO] [device.py:recv_hello] Received nonce: b'\x93r\x15\xb3.\xf8E\xc8\xec\x8bM\x9a\x80\xdf]\xb1'
2025-06-08 14:44:48,642 [INFO] [device.py:recv_hello] Sent acknowledgement
2025-06-08 14:44:48,642 [INFO] [device.py:send_pre_master_secret] Sent pre-master secret
2025-06-08 14:44:48,643 [INFO] [server.py:send_hello] Device acknowledgement: NONCE_RECEIVED
2025-06-08 14:44:48,643 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:44:48,643 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:44:48,643 [INFO] [server.py:<module>] Received header: b'<PREM>'
2025-06-08 14:44:48,643 [INFO] [server.py:<module>] Expecting pre-master secret
2025-06-08 14:44:48,643 [INFO] [server.py:recv_exact] Receiving exactly 256 bytes...
2025-06-08 14:44:48,643 [INFO] [server.py:recv_exact] Received 256 bytes successfully
2025-06-08 14:44:48,644 [INFO] [server.py:<module>] Received pre-master secret: b'[\xcf\xe0\x10\xb0\xbdu\xe79\xcc\xb0\xa9\x11m\xf4\xbc\x0c@\x18\x17H\x15\xe7\xdc\xab\xb4\xc8\xb0D\xf6\xe3\xa3'
2025-06-08 14:44:48,644 [INFO] [server.py:<module>] Sent acknowledgement
2025-06-08 14:44:48,644 [INFO] [server.py:<module>] Nonce device: b'\x88!\x8cz\xd7c\x84:\xc9%\x00\x9e\x94\x14\x11\x18'
2025-06-08 14:44:48,644 [INFO] [server.py:<module>] Nonce server: b'\x93r\x15\xb3.\xf8E\xc8\xec\x8bM\x9a\x80\xdf]\xb1'
2025-06-08 14:44:48,645 [INFO] [server.py:<module>] Derived keys: {'client_enc_key': b'$\xfcy\xb7@\x99O\xddB1\n\xb31\x8d\xf4\xaa', 'server_enc_key': b'Z\x1a\xd9 \xbe\xae\x89\r\xc2\xb0^\xe2\xc2\x90yA', 'client_mac_key': b'\xef\xb5\x81\x1bF3/8z\xe6\xf2\x03\xfc\x1bv\x94', 'server_mac_key': b'\xe11\xee\xf1=\x82t\x11\xc9\xd7\xec\x113"\xd0\xbe', 'iv': b'\x81\xca\xa1j\xb5\x84\xfb9\x1e?A\x1bR\xad\xc9y'}
2025-06-08 14:44:48,645 [INFO] [server.py:recv_exact] Receiving exactly 6 bytes...
2025-06-08 14:44:48,646 [INFO] [device.py:send_pre_master_secret] Server acknowledgement: PREM_RECEIVED
2025-06-08 14:44:48,646 [INFO] [device.py:send_end_of_file] Sent header: END
2025-06-08 14:44:48,646 [INFO] [server.py:recv_exact] Received 6 bytes successfully
2025-06-08 14:44:48,646 [INFO] [device.py:<module>] Derived keys: {'client_enc_key': b'$\xfcy\xb7@\x99O\xddB1\n\xb31\x8d\xf4\xaa', 'server_enc_key': b'Z\x1a\xd9 \xbe\xae\x89\r\xc2\xb0^\xe2\xc2\x90yA', 'client_mac_key': b'\xef\xb5\x81\x1bF3/8z\xe6\xf2\x03\xfc\x1bv\x94', 'server_mac_key': b'\xe11\xee\xf1=\x82t\x11\xc9\xd7\xec\x113"\xd0\xbe', 'iv': b'\x81\xca\xa1j\xb5\x84\xfb9\x1e?A\x1bR\xad\xc9y'}
2025-06-08 14:44:48,646 [INFO] [server.py:<module>] Received header: b'<ENDD>'
2025-06-08 14:44:48,646 [INFO] [device.py:<module>] Device socket closed
2025-06-08 14:44:48,646 [INFO] [server.py:<module>] Received end of file
2025-06-08 14:44:48,646 [INFO] [server.py:<module>] Server closed
2025-06-08 14:44:48,646 [INFO] [server.py:<module>] Server shut down
